---
# Role tasks
- block:

    - include_tasks: selinux.yml
      when:
        - ansible_selinux is defined
        - ansible_selinux.status != 'disabled'

    - include_tasks: install.yml

  tags:
    - role::clamav
