---

- name: Setup clamav
  block:
    - ansible.builtin.include_tasks: selinux.yml
      when:
        - ansible_facts.selinux is defined
        - ansible_facts.selinux.status != 'disabled'

    - ansible.builtin.include_tasks: install.yml
  tags:
    - role::clamav
