---
# Role tasks

- block:
    - include_tasks: selinux.yml
      when:
        - ansible_facts.selinux is defined
        - ansible_facts.selinux.status != 'disabled'

    - include_tasks: install.yml
  tags:
    - role::clamav
