---
# Role handlers

- name: Restart ClamAV service
  systemd:
    name: clamd@scan.service
    state: restarted
    daemon_reload: yes
  listen: restart clamav
  tags:
    - role::clamav
    - role::clamav::restart
