---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  roles:
    - role: amtega.clamav
      vars:
        clamav_local_socket: /var/run/clamd.scan/clamd.sock
        clamav_local_socket_group: virusgroup
        clamav_local_socket_mode: 660
        clamav_pid_file: /var/run/clamd.scan/clamd.pid
