---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos

  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/8
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos

  - name: "fedora32-${INSTANCE_UUID:-1}"
    box: fedora/32-cloud-base
    memory: 3072
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          clamav_max_directory_recursion: 0
          clamav_local_socket: /var/run/clamd.scan/clamd.sock
          clamav_local_socket_group: virusgroup
          clamav_local_socket_mode: 660
          clamav_pid_file: /var/run/clamd.scan/clamd.pid
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
