---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
  # - name: "fedora29-${INSTANCE_UUID:-1}"
  #   box: fedora/29-cloud-base
  #   memory: 1536
  #   groups:
  #     - molecule_hosts
  #     - molecule_hosts_fedora
  - name: "fedora30-${INSTANCE_UUID:-1}"
    box: fedora/30-cloud-base
    memory: 3072
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

  - name: "fedora31-${INSTANCE_UUID:-1}"
    box: fedora/31-cloud-base
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_fedora

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          clamav_max_directory_recursion: 0
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
