---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Gather service facts
      service_facts:
      register: clamav_services_state

    - name: Assert ClamAV services are running
      assert:
        that:
          - clamav_freshclam_state == "running"
      vars:
        clamav_freshclam_state: >-
          {{ ansible_facts.services['freshclam.service'].state }}
