---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Gather service facts
      service_facts:
      register: clamav_services_state

    - name: Assert ClamAV freshclam services are running
      assert:
        that:
          - clamav_freshclam_state == "running"
      vars:
        clamav_freshclam_state: >-
          {{ ansible_facts.services['freshclam.service'].state }}

    - name: Assert ClamAV clamd services are running
      assert:
        that:
          - clamav_scan_state == "running"
      vars:
        clamav_scan_state: >-
          {{ ansible_facts.services['clamd@scan.service'].state }}
